# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-03 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0009_recipe_serves'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='liked',
            field=models.BooleanField(default=True, verbose_name='Whether the recipe was liked'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='slow_cooker_friendly',
            field=models.BooleanField(default=False, verbose_name='Whether the meal is suitable for a slow cooker'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='typical_meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cookery.MealTime'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'beginner'), (1, 'intermediate'), (2, 'expert'), (3, 'world class'), (None, 'unknown')], default=0, null=True, verbose_name='Difficulty'),
        ),
    ]
